# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Chuck/RVfpga/src/liteDRAM.xdc

# XDC: C:/Users/Chuck/RVfpga/src/rvfpga.xdc

# IP: ip/clk_gen_75M/clk_gen_75M.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_gen_75M || ORIG_REF_NAME==clk_gen_75M} -quiet] -quiet
